// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// MockDatabaseSQLService is an autogenerated mock type for the DatabaseSQLService type
type MockDatabaseSQLService struct {
	mock.Mock
}

// GetDbName provides a mock function with given fields:
func (_m *MockDatabaseSQLService) GetDbName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDbName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetInstance provides a mock function with given fields:
func (_m *MockDatabaseSQLService) GetInstance() *sql.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 *sql.DB
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	return r0
}

// Ping provides a mock function with given fields: ctx
func (_m *MockDatabaseSQLService) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockDatabaseSQLService creates a new instance of MockDatabaseSQLService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabaseSQLService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabaseSQLService {
	mock := &MockDatabaseSQLService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
