name: destroy

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.3"

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_TF_STATE }}"

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false
        continue-on-error: true

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          terraform destroy -input=false -auto-approve \
          -var="access_key=${{ secrets.AWS_ACCESS_KEY }}" \
          -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \